# Generated by Django 4.0.4 on 2022-05-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_ko', models.CharField(max_length=30)),
                ('company_en', models.CharField(max_length=30)),
                ('company_ja', models.CharField(max_length=30)),
                ('tag_ko', models.CharField(max_length=30)),
                ('tag_en', models.CharField(max_length=30)),
                ('tag_ja', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
